### ISSUE TITLE
Feature request - Forwarded events

### ISSUE THREAD

**Issue by Tomasinjo** [0xrawsec/whids#2]
Hi,
Can you please add ability to run Whids on Forwarded Events?

Regards,
Tom

**Comment by qjerome** [comment]
Hi Tom,

It should be already working. Actually you can listen on more channels than the ones proposed in the help. The ones that you see in the help are just aliases (i.e. shortcuts) to make things easier but theoretically you can listen on absolutely any channel you want. In order to know the channel name to use, you can open the Event Viewer -> Right Click on Channel you like -> Properties -> Remember (copy-paste) the field **Full Name** -> use it with the **-c** command line switch of WHIDS. If you prefer CLI, you can find the correct channel issuing **wevtutil.exe el** and grep out the result.

According to what I have already tested in the past, you should be able to listen on Forwarded Event channel running **WHIDS** with option **-c ForwardedEvents**.  

I can still add an alias for that channel in the next release but it should be already working.

Please let me know when you have tested.

Cheers,

**Comment by Tomasinjo** [comment]
Thank you for quick response.
I can confirm that above suggestion works!

I really like what you did. Keep it up!

**Comment by qjerome** [comment]
You're welcome, and thanks for the supporting message!
Don't hesitate to let me know if you'd like to see some features in the next release of the tool.
